/**
 * @file
 *   CSV_READER Application Topic IDs
 */
#ifndef CSV_READER_TOPICIDS_H
#define CSV_READER_TOPICIDS_H

#include "csv_reader_topicid_values.h"

#define DEFAULT_CSV_READER_MISSION_CMD_TOPICID    0x8C
#define DEFAULT_CSV_READER_MISSION_HK_TLM_TOPICID 0x8D

#define CSV_READER_MISSION_CMD_TOPICID    CSV_READER_MISSION_TIDVAL(CMD)
#define CSV_READER_MISSION_HK_TLM_TOPICID CSV_READER_MISSION_TIDVAL(HK_TLM)

#endif
