#ifndef CSV_READER_EVENTIDS_H
#define CSV_READER_EVENTIDS_H

#define CSV_READER_INIT_FAILURE_EID     1
#define CSV_READER_INIT_SUCCESSFUL_EID  2
#define CSV_READER_HK_TRANSMIT_ERR_EID  3

#define CSV_READER_NOOP_EID             4
#define CSV_READER_RESET_COUNTERS_EID   5
#define CSV_READER_INVALID_MID_EID      6
#define CSV_READER_INVALID_CC_EID       7

#define CSV_READER_FILE_OPEN_ERR_EID    8
#define CSV_READER_FILE_READ_SUCCESS_EID 9
#define CSV_READER_FILE_EMPTY_EID       10

#endif
