#ifndef DEFAULT_CMD_HAND_MSGIDS_H
#define DEFAULT_CMD_HAND_MSGIDS_H

#define CMD_HAND_CMD_MID 0x186F
#define CMD_HAND_SEND_HK_MID 112

#define CMD_HAND_HK_TLM_MID 113

#define CMD_HAND_LISTENING_PORT 1234

#endif
