#ifndef PAYLOAD_APP_EVENTIDS_H
#define PAYLOAD_APP_EVENTIDS_H

#define PAYLOAD_APP_INIT_FAILURE_EID     1
#define PAYLOAD_APP_INIT_SUCCESSFUL_EID  2
#define PAYLOAD_APP_HK_TRANSMIT_ERR_EID  3

#define PAYLOAD_APP_NOOP_EID             4
#define PAYLOAD_APP_RESET_COUNTERS_EID   5
#define PAYLOAD_APP_INVALID_MID_EID      6
#define PAYLOAD_APP_INVALID_CC_EID       7

#define PAYLOAD_APP_SOCKET_CONNECT_ERR_EID    8
#define PAYLOAD_APP_SOCKET_CONNECTED_EID      9
#define PAYLOAD_APP_SOCKET_DISCONNECTED_EID   10
#define PAYLOAD_APP_SOCKET_PARSE_ERR_EID      11
#define PAYLOAD_APP_DATA_TLM_TRANSMIT_ERR_EID 12

#endif
