/**
 * @file
 *   PAYLOAD_APP Application Topic IDs
 */
#ifndef PAYLOAD_APP_TOPICIDS_H
#define PAYLOAD_APP_TOPICIDS_H

#include "payload_app_topicid_values.h"

#define DEFAULT_PAYLOAD_APP_MISSION_CMD_TOPICID    0x8C
#define DEFAULT_PAYLOAD_APP_MISSION_HK_TLM_TOPICID 0x8D

#define PAYLOAD_APP_MISSION_CMD_TOPICID    PAYLOAD_APP_MISSION_TIDVAL(CMD)
#define PAYLOAD_APP_MISSION_HK_TLM_TOPICID PAYLOAD_APP_MISSION_TIDVAL(HK_TLM)

#endif
