#ifndef PAYLOAD_APP_EVENTIDS_H
#define PAYLOAD_APP_EVENTIDS_H

#define PAYLOAD_APP_INIT_FAILURE_EID     1
#define PAYLOAD_APP_INIT_SUCCESSFUL_EID  2
#define PAYLOAD_APP_HK_TRANSMIT_ERR_EID  3

#define PAYLOAD_APP_NOOP_EID             4
#define PAYLOAD_APP_RESET_COUNTERS_EID   5
#define PAYLOAD_APP_INVALID_MID_EID      6
#define PAYLOAD_APP_INVALID_CC_EID       7

#define PAYLOAD_APP_FILE_OPEN_ERR_EID    8
#define PAYLOAD_APP_FILE_READ_SUCCESS_EID 9
#define PAYLOAD_APP_FILE_EMPTY_EID       10

#endif
