/**
 * @file
 *   PAYLOAD_APP Application Message IDs
 */
#ifndef DEFAULT_PAYLOAD_APP_MSGIDS_H
#define DEFAULT_PAYLOAD_APP_MSGIDS_H

#include "cfe_core_api_base_msgids.h"

#define PAYLOAD_APP_CMD_MID         PAYLOAD_APP_CMD_PLATFORM_MIDVAL(CMD)
#define PAYLOAD_APP_TLM_MID         PAYLOAD_APP_TLM_PLATFORM_MIDVAL(HK_TLM)
#define PAYLOAD_APP_DATA_TLM_MID    PAYLOAD_APP_TLM_PLATFORM_MIDVAL(DATA_TLM)    /* one per live aircraft */
#define PAYLOAD_APP_SESSION_TLM_MID PAYLOAD_APP_TLM_PLATFORM_MIDVAL(SESSION_TLM) /* LIST_SESSIONS / GET_SESSION_INFO */
#define PAYLOAD_APP_CHUNK_TLM_MID   PAYLOAD_APP_TLM_PLATFORM_MIDVAL(CHUNK_TLM)   /* READ_SESSION_RANGE bytes */

#endif
