#ifndef NARWAL_THERMAL_ZONES_CONFIG_H
#define NARWAL_THERMAL_ZONES_CONFIG_H

#define NARWAL_THERMAL_ZONE_PATH_MAX 100
#define NARWAL_THERMAL_ZONE_THERMAL_DIR "/sys/class/thermal/"

#define NARWAL_THERMAL_ZONE_TYPE_MAX 20
#define NARWAL_THERMAL_ZONE_TEMP_MAX 6
#define NARWAL_THERMAL_ZONE_TEMPERATURE_CELCIUS

#endif

