#ifndef DEFAULT_TELECOM_MSGID_H
#define DEFAULT_TELECOM_MSGID_H

#define TELECOM_CMD_MID      0x187A 
#define TELECOM_SEND_HK_MID  123 

#define TELECOM_HK_TLM_MID   124
#define TELECOM_OPEN_TLM_MID 125 

#endif
