#ifndef CMD_HAND_EVENTIDS_H
#define CMD_HAND_EVENTIDS_H

#define CMD_HAND_SUCCESS_EID               0
#define CMD_HAND_SUBSCRIPTION_CMD_ERR_EID  1
#define CMD_HAND_PIPE_CREATION_ERR_EID     2
#define CMD_HAND_OPENING_SOCKET_ERR        3
#define CMD_HAND_BINDING_SOCKET_ERR        4
#define CMD_HAND_INGEST_BUF_ALLOC_ERR      5
#define CMD_HAND_INGEST_LENGTH_ERR_EID     6
#define CMD_HAND_INGEST_SEND_ERR_EID       7

#endif
